
CREATE TABLE marca (
	id auto_increment primary key,
	descricao varchar(30) not null
);

CREATE TABLE marca_modelo (
	id auto_increment primary key,
	marca_id int not null,
	descricao varchar(30) not null,
	foreign key (marca_id) references marca(id)
);

insert into marca (descricao) values('CHEVROLET');
insert into marca (descricao) values('CITROËN');
insert into marca (descricao) values('FIAT');
insert into marca (descricao) values('FORD');
insert into marca (descricao) values('HONDA');
insert into marca (descricao) values('MITSUBISHI');
insert into marca (descricao) values('PEUGEOT');
insert into marca (descricao) values('RENAULT');
insert into marca (descricao) values('TOYOTA');
insert into marca (descricao) values('VOLKSWAGEN');
insert into marca (descricao) values('');
insert into marca (descricao) values('ACURA');
insert into marca (descricao) values('ADAMO');
insert into marca (descricao) values('AGRALE');
insert into marca (descricao) values('ALFA ROMEO');
insert into marca (descricao) values('AMERICAR');
insert into marca (descricao) values('ASIA');
insert into marca (descricao) values('ASTON MARTIN');
insert into marca (descricao) values('AUDI');
insert into marca (descricao) values('AUSTIN');
insert into marca (descricao) values('BAJA');
insert into marca (descricao) values('BEACH');
insert into marca (descricao) values('BENTLEY');
insert into marca (descricao) values('BIANCO');
insert into marca (descricao) values('BMW');
insert into marca (descricao) values('BRM');
insert into marca (descricao) values('BUGWAY');
insert into marca (descricao) values('BUICK');
insert into marca (descricao) values('CADILLAC');
insert into marca (descricao) values('CBT');
insert into marca (descricao) values('CHAMONIX');
insert into marca (descricao) values('CHANA');
insert into marca (descricao) values('CHRYSLER');
insert into marca (descricao) values('CORD');
insert into marca (descricao) values('CROSS LANDER');
insert into marca (descricao) values('DAEWOO');
insert into marca (descricao) values('DAIHATSU');
insert into marca (descricao) values('DKW-VEMAG');
insert into marca (descricao) values('DODGE');
insert into marca (descricao) values('DUNNAS');
insert into marca (descricao) values('EFFA');
insert into marca (descricao) values('ENGESA');
insert into marca (descricao) values('ENVEMO');
insert into marca (descricao) values('FARUS');
insert into marca (descricao) values('FERRARI');
insert into marca (descricao) values('FNM');
insert into marca (descricao) values('FYBER');
insert into marca (descricao) values('GEO');
insert into marca (descricao) values('GMC');
insert into marca (descricao) values('GRANCAR VEÍCULOS');
insert into marca (descricao) values('GURGEL');
insert into marca (descricao) values('HUMMER');
insert into marca (descricao) values('HYUNDAI');
insert into marca (descricao) values('INFINITI');
insert into marca (descricao) values('INTERNATIONAL');
insert into marca (descricao) values('ISUZU');
insert into marca (descricao) values('IVECO');
insert into marca (descricao) values('JAGUAR');
insert into marca (descricao) values('JEEP');
insert into marca (descricao) values('JPX');
insert into marca (descricao) values('KIA');
insert into marca (descricao) values('LADA');
insert into marca (descricao) values('LAMBORGHINI');
insert into marca (descricao) values('LANCIA');
insert into marca (descricao) values('LAND ROVER');
insert into marca (descricao) values('LEXUS');
insert into marca (descricao) values('LINCOLN');
insert into marca (descricao) values('LOBINI');
insert into marca (descricao) values('LOTUS');
insert into marca (descricao) values('MARCOPOLO');
insert into marca (descricao) values('MARINA´S');
insert into marca (descricao) values('MASERATI');
insert into marca (descricao) values('MATRA');
insert into marca (descricao) values('MAZDA');
insert into marca (descricao) values('MERCEDES-BENZ');
insert into marca (descricao) values('MERCURY');
insert into marca (descricao) values('MG');
insert into marca (descricao) values('MINI');
insert into marca (descricao) values('MIURA');
insert into marca (descricao) values('MORRIS');
insert into marca (descricao) values('MP LAFER');
insert into marca (descricao) values('NISSAN');
insert into marca (descricao) values('OLDSMOBILE');
insert into marca (descricao) values('OPEL');
insert into marca (descricao) values('PLYMOUTH');
insert into marca (descricao) values('PONTIAC');
insert into marca (descricao) values('PORSCHE');
insert into marca (descricao) values('PUMA');
insert into marca (descricao) values('ROLLS-ROYCE');
insert into marca (descricao) values('ROMI');
insert into marca (descricao) values('ROVER');
insert into marca (descricao) values('SAAB');
insert into marca (descricao) values('SANTA MATILDE');
insert into marca (descricao) values('SATURN');
insert into marca (descricao) values('SEAT');
insert into marca (descricao) values('SHELBY');
insert into marca (descricao) values('SHORT');
insert into marca (descricao) values('SIMCA');
insert into marca (descricao) values('SMART');
insert into marca (descricao) values('SSANGYONG');
insert into marca (descricao) values('STUDEBAKER');
insert into marca (descricao) values('SUBARU');
insert into marca (descricao) values('SUZUKI');
insert into marca (descricao) values('TROLLER');
insert into marca (descricao) values('UNIMOG');
insert into marca (descricao) values('VOLVO');
insert into marca (descricao) values('WALK');
insert into marca (descricao) values('WILLYS');

-------------------------------------------------------------------------------------------

insert into marca_modelo (marca_id, descricao) values('1','ZAFIRA');
insert into marca_modelo (marca_id, descricao) values('1','RAMONA');
insert into marca_modelo (marca_id, descricao) values('1','PRISMA');
insert into marca_modelo (marca_id, descricao) values('1','PICKUP');
insert into marca_modelo (marca_id, descricao) values('1','OPALA');
insert into marca_modelo (marca_id, descricao) values('1','OMEGA');
insert into marca_modelo (marca_id, descricao) values('1','MONZA');
insert into marca_modelo (marca_id, descricao) values('1','MONTANA');
insert into marca_modelo (marca_id, descricao) values('1','MERIVA');
insert into marca_modelo (marca_id, descricao) values('1','MARAJÓ');
insert into marca_modelo (marca_id, descricao) values('1','LUMINA');
insert into marca_modelo (marca_id, descricao) values('1','KADETT');
insert into marca_modelo (marca_id, descricao) values('1','IPANEMA');
insert into marca_modelo (marca_id, descricao) values('1','IMPALA');
insert into marca_modelo (marca_id, descricao) values('1','S10');
insert into marca_modelo (marca_id, descricao) values('1','S10 4X4');
insert into marca_modelo (marca_id, descricao) values('1','SATURN');
insert into marca_modelo (marca_id, descricao) values('1','VERANEIO');
insert into marca_modelo (marca_id, descricao) values('1','VECTRA');
insert into marca_modelo (marca_id, descricao) values('1','TRAFIC');
insert into marca_modelo (marca_id, descricao) values('1','TRACKER');
insert into marca_modelo (marca_id, descricao) values('1','TIGRA');
insert into marca_modelo (marca_id, descricao) values('1','SYCLONE');
insert into marca_modelo (marca_id, descricao) values('1','SUPREMA');
insert into marca_modelo (marca_id, descricao) values('1','SUBURBAN');
insert into marca_modelo (marca_id, descricao) values('1','SSR');
insert into marca_modelo (marca_id, descricao) values('1','SS');
insert into marca_modelo (marca_id, descricao) values('1','SPORT VAN');
insert into marca_modelo (marca_id, descricao) values('1','SPACE VAN');
insert into marca_modelo (marca_id, descricao) values('1','SILVERADO');
insert into marca_modelo (marca_id, descricao) values('1','GRAND BLAZER');
insert into marca_modelo (marca_id, descricao) values('1','FLEETLINE');
insert into marca_modelo (marca_id, descricao) values('1','D40');
insert into marca_modelo (marca_id, descricao) values('1','C20');
insert into marca_modelo (marca_id, descricao) values('1','C15');
insert into marca_modelo (marca_id, descricao) values('1','C14');
insert into marca_modelo (marca_id, descricao) values('1','C10');
insert into marca_modelo (marca_id, descricao) values('1','BUICK');
insert into marca_modelo (marca_id, descricao) values('1','BRASINCA');
insert into marca_modelo (marca_id, descricao) values('1','BONANZA');
insert into marca_modelo (marca_id, descricao) values('1','BLAZER');
insert into marca_modelo (marca_id, descricao) values('1','BEL AIR');
insert into marca_modelo (marca_id, descricao) values('1','ASTROVAN');
insert into marca_modelo (marca_id, descricao) values('1','ASTRA');
insert into marca_modelo (marca_id, descricao) values('1','A20');
insert into marca_modelo (marca_id, descricao) values('1','A10');
insert into marca_modelo (marca_id, descricao) values('1','3100');
insert into marca_modelo (marca_id, descricao) values('1','CALIBRA');
insert into marca_modelo (marca_id, descricao) values('1','CAMARO');
insert into marca_modelo (marca_id, descricao) values('1','D20');
insert into marca_modelo (marca_id, descricao) values('1','D10');
insert into marca_modelo (marca_id, descricao) values('1','CORVETTE');
insert into marca_modelo (marca_id, descricao) values('1','CORSICA');
insert into marca_modelo (marca_id, descricao) values('1','CORSA');
insert into marca_modelo (marca_id, descricao) values('1','COLORADO');
insert into marca_modelo (marca_id, descricao) values('1','CLASSIC');
insert into marca_modelo (marca_id, descricao) values('1','CHEVY 500');
insert into marca_modelo (marca_id, descricao) values('1','CAPRICE');
insert into marca_modelo (marca_id, descricao) values('1','CARAVAN');
insert into marca_modelo (marca_id, descricao) values('1','CAVALIER');
insert into marca_modelo (marca_id, descricao) values('1','CELTA');
insert into marca_modelo (marca_id, descricao) values('1','CHEVELLE');
insert into marca_modelo (marca_id, descricao) values('1','CHEVETTE');
insert into marca_modelo (marca_id, descricao) values('2','EVASION');
insert into marca_modelo (marca_id, descricao) values('2','JUMPER');
insert into marca_modelo (marca_id, descricao) values('2','XANTIA');
insert into marca_modelo (marca_id, descricao) values('2','XM');
insert into marca_modelo (marca_id, descricao) values('2','XSARA');
insert into marca_modelo (marca_id, descricao) values('2','XSARA PICASSO');
insert into marca_modelo (marca_id, descricao) values('2','ZX');
insert into marca_modelo (marca_id, descricao) values('2','C8');
insert into marca_modelo (marca_id, descricao) values('2','C6');
insert into marca_modelo (marca_id, descricao) values('2','3 CV');
insert into marca_modelo (marca_id, descricao) values('2','AX');
insert into marca_modelo (marca_id, descricao) values('2','BERLINGO');
insert into marca_modelo (marca_id, descricao) values('2','BX');
insert into marca_modelo (marca_id, descricao) values('2','C3');
insert into marca_modelo (marca_id, descricao) values('2','C4');
insert into marca_modelo (marca_id, descricao) values('2','C5');
insert into marca_modelo (marca_id, descricao) values('3','OGGI');
insert into marca_modelo (marca_id, descricao) values('3','PALIO');
insert into marca_modelo (marca_id, descricao) values('3','PANORAMA');
insert into marca_modelo (marca_id, descricao) values('3','PREMIO');
insert into marca_modelo (marca_id, descricao) values('3','PUNTO');
insert into marca_modelo (marca_id, descricao) values('3','SIENA');
insert into marca_modelo (marca_id, descricao) values('3','SPAZIO');
insert into marca_modelo (marca_id, descricao) values('3','STILO');
insert into marca_modelo (marca_id, descricao) values('3','STRADA');
insert into marca_modelo (marca_id, descricao) values('3','TEMPRA');
insert into marca_modelo (marca_id, descricao) values('3','TIPO');
insert into marca_modelo (marca_id, descricao) values('3','UNO');
insert into marca_modelo (marca_id, descricao) values('3','NOVO DUCATO');
insert into marca_modelo (marca_id, descricao) values('3','MAREA');
insert into marca_modelo (marca_id, descricao) values('3','IDEA');
insert into marca_modelo (marca_id, descricao) values('3','124');
insert into marca_modelo (marca_id, descricao) values('3','147');
insert into marca_modelo (marca_id, descricao) values('3','600');
insert into marca_modelo (marca_id, descricao) values('3','BRAVA');
insert into marca_modelo (marca_id, descricao) values('3','CINQUECENTO');
insert into marca_modelo (marca_id, descricao) values('3','COUPÉ');
insert into marca_modelo (marca_id, descricao) values('3','DARDO');
insert into marca_modelo (marca_id, descricao) values('3','FIORINO');
insert into marca_modelo (marca_id, descricao) values('3','ELBA');
insert into marca_modelo (marca_id, descricao) values('3','DUNA');
insert into marca_modelo (marca_id, descricao) values('3','DUCATO');
insert into marca_modelo (marca_id, descricao) values('3','DOBLÒ');
insert into marca_modelo (marca_id, descricao) values('4','CONTOUR');
insert into marca_modelo (marca_id, descricao) values('4','CORCEL');
insert into marca_modelo (marca_id, descricao) values('4','CORCEL II');
insert into marca_modelo (marca_id, descricao) values('4','COURIER');
insert into marca_modelo (marca_id, descricao) values('4','CROWN VICTORIA');
insert into marca_modelo (marca_id, descricao) values('4','CUPÊ');
insert into marca_modelo (marca_id, descricao) values('4','DEL REY');
insert into marca_modelo (marca_id, descricao) values('4','ECOSPORT');
insert into marca_modelo (marca_id, descricao) values('4','ESCORT');
insert into marca_modelo (marca_id, descricao) values('4','EXPEDITION');
insert into marca_modelo (marca_id, descricao) values('4','EXPLORER');
insert into marca_modelo (marca_id, descricao) values('4','CONSUL');
insert into marca_modelo (marca_id, descricao) values('4','COBRA');
insert into marca_modelo (marca_id, descricao) values('4','CLUB WAGON');
insert into marca_modelo (marca_id, descricao) values('4','WINDSTAR');
insert into marca_modelo (marca_id, descricao) values('4','VICTORIA');
insert into marca_modelo (marca_id, descricao) values('4','VERSAILLES');
insert into marca_modelo (marca_id, descricao) values('4','VERONA');
insert into marca_modelo (marca_id, descricao) values('4','TUDOR');
insert into marca_modelo (marca_id, descricao) values('4','THUNDERBIRD');
insert into marca_modelo (marca_id, descricao) values('4','TAURUS');
insert into marca_modelo (marca_id, descricao) values('4','RURAL');
insert into marca_modelo (marca_id, descricao) values('4','AEROSTAR');
insert into marca_modelo (marca_id, descricao) values('4','ASPIRE');
insert into marca_modelo (marca_id, descricao) values('4','BELINA');
insert into marca_modelo (marca_id, descricao) values('4','EXPLORER XLT');
insert into marca_modelo (marca_id, descricao) values('4','F-1');
insert into marca_modelo (marca_id, descricao) values('4','JEEP');
insert into marca_modelo (marca_id, descricao) values('4','KA');
insert into marca_modelo (marca_id, descricao) values('4','LANDAU');
insert into marca_modelo (marca_id, descricao) values('4','MAVERICK');
insert into marca_modelo (marca_id, descricao) values('4','MUSTANG');
insert into marca_modelo (marca_id, descricao) values('4','ROYALE');
insert into marca_modelo (marca_id, descricao) values('4','RANGER');
insert into marca_modelo (marca_id, descricao) values('4','PROBE');
insert into marca_modelo (marca_id, descricao) values('4','PAMPA');
insert into marca_modelo (marca_id, descricao) values('4','MONDEO');
insert into marca_modelo (marca_id, descricao) values('4','MODELO T');
insert into marca_modelo (marca_id, descricao) values('4','IBIZA');
insert into marca_modelo (marca_id, descricao) values('4','GALAXIE');
insert into marca_modelo (marca_id, descricao) values('4','F-100');
insert into marca_modelo (marca_id, descricao) values('4','F-1000');
insert into marca_modelo (marca_id, descricao) values('4','F-150');
insert into marca_modelo (marca_id, descricao) values('4','F-250');
insert into marca_modelo (marca_id, descricao) values('4','F-350');
insert into marca_modelo (marca_id, descricao) values('4','F-75');
insert into marca_modelo (marca_id, descricao) values('4','F3 PICK UP');
insert into marca_modelo (marca_id, descricao) values('4','FIESTA');
insert into marca_modelo (marca_id, descricao) values('4','FOCUS');
insert into marca_modelo (marca_id, descricao) values('4','FURGLAINE');
insert into marca_modelo (marca_id, descricao) values('4','FUSION');
insert into marca_modelo (marca_id, descricao) values('4','MODELO A');
insert into marca_modelo (marca_id, descricao) values('5','PRELUDE');
insert into marca_modelo (marca_id, descricao) values('5','ACCORD');
insert into marca_modelo (marca_id, descricao) values('5','CIVIC');
insert into marca_modelo (marca_id, descricao) values('5','CRV');
insert into marca_modelo (marca_id, descricao) values('5','FIT');
insert into marca_modelo (marca_id, descricao) values('5','LEGEND');
insert into marca_modelo (marca_id, descricao) values('5','ODYSSEY');
insert into marca_modelo (marca_id, descricao) values('5','PASSPORT');
insert into marca_modelo (marca_id, descricao) values('6','SPACE WAGON');
insert into marca_modelo (marca_id, descricao) values('6','PAJERO');
insert into marca_modelo (marca_id, descricao) values('6','OUTLANDER');
insert into marca_modelo (marca_id, descricao) values('6','MONTERO');
insert into marca_modelo (marca_id, descricao) values('6','MIRAGE');
insert into marca_modelo (marca_id, descricao) values('6','3000 GT');
insert into marca_modelo (marca_id, descricao) values('6','AIRTREK');
insert into marca_modelo (marca_id, descricao) values('6','COLT');
insert into marca_modelo (marca_id, descricao) values('6','DIAMANT');
insert into marca_modelo (marca_id, descricao) values('6','ECLIPSE');
insert into marca_modelo (marca_id, descricao) values('6','EXPO');
insert into marca_modelo (marca_id, descricao) values('6','GALANT');
insert into marca_modelo (marca_id, descricao) values('6','GRANDIS');
insert into marca_modelo (marca_id, descricao) values('6','LANCER');
insert into marca_modelo (marca_id, descricao) values('6','L300');
insert into marca_modelo (marca_id, descricao) values('6','L200');
insert into marca_modelo (marca_id, descricao) values('7','309');
insert into marca_modelo (marca_id, descricao) values('7','GRD');
insert into marca_modelo (marca_id, descricao) values('7','PARTNER');
insert into marca_modelo (marca_id, descricao) values('7','306');
insert into marca_modelo (marca_id, descricao) values('7','206');
insert into marca_modelo (marca_id, descricao) values('7','205');
insert into marca_modelo (marca_id, descricao) values('7','106');
insert into marca_modelo (marca_id, descricao) values('7','807');
insert into marca_modelo (marca_id, descricao) values('7','GD');
insert into marca_modelo (marca_id, descricao) values('7','BOXER');
insert into marca_modelo (marca_id, descricao) values('7','320');
insert into marca_modelo (marca_id, descricao) values('7','405');
insert into marca_modelo (marca_id, descricao) values('7','406');
insert into marca_modelo (marca_id, descricao) values('7','407');
insert into marca_modelo (marca_id, descricao) values('7','504');
insert into marca_modelo (marca_id, descricao) values('7','505');
insert into marca_modelo (marca_id, descricao) values('7','605');
insert into marca_modelo (marca_id, descricao) values('7','607');
insert into marca_modelo (marca_id, descricao) values('7','806');
insert into marca_modelo (marca_id, descricao) values('7','307');
insert into marca_modelo (marca_id, descricao) values('8','807');
insert into marca_modelo (marca_id, descricao) values('8','BOXER');
insert into marca_modelo (marca_id, descricao) values('8','GD');
insert into marca_modelo (marca_id, descricao) values('8','GRD');
insert into marca_modelo (marca_id, descricao) values('8','PARTNER');
insert into marca_modelo (marca_id, descricao) values('8','806');
insert into marca_modelo (marca_id, descricao) values('8','607');
insert into marca_modelo (marca_id, descricao) values('8','106');
insert into marca_modelo (marca_id, descricao) values('8','205');
insert into marca_modelo (marca_id, descricao) values('8','206');
insert into marca_modelo (marca_id, descricao) values('8','306');
insert into marca_modelo (marca_id, descricao) values('8','307');
insert into marca_modelo (marca_id, descricao) values('8','309');
insert into marca_modelo (marca_id, descricao) values('8','320');
insert into marca_modelo (marca_id, descricao) values('8','405');
insert into marca_modelo (marca_id, descricao) values('8','605');
insert into marca_modelo (marca_id, descricao) values('8','505');
insert into marca_modelo (marca_id, descricao) values('8','504');
insert into marca_modelo (marca_id, descricao) values('8','407');
insert into marca_modelo (marca_id, descricao) values('8','406');
insert into marca_modelo (marca_id, descricao) values('9','LEXUS');
insert into marca_modelo (marca_id, descricao) values('9','MR-2');
insert into marca_modelo (marca_id, descricao) values('9','PASEO');
insert into marca_modelo (marca_id, descricao) values('9','PREVIA');
insert into marca_modelo (marca_id, descricao) values('9','RAV4');
insert into marca_modelo (marca_id, descricao) values('9','SIENNA');
insert into marca_modelo (marca_id, descricao) values('9','SUPRA');
insert into marca_modelo (marca_id, descricao) values('9','T-100');
insert into marca_modelo (marca_id, descricao) values('9','TUNDRA');
insert into marca_modelo (marca_id, descricao) values('9','LAND CRUISER PRADO');
insert into marca_modelo (marca_id, descricao) values('9','LAND');
insert into marca_modelo (marca_id, descricao) values('9','HILUX SW4');
insert into marca_modelo (marca_id, descricao) values('9','4RUNNER');
insert into marca_modelo (marca_id, descricao) values('9','BANDEIRANTE');
insert into marca_modelo (marca_id, descricao) values('9','BJ');
insert into marca_modelo (marca_id, descricao) values('9','CAMRY');
insert into marca_modelo (marca_id, descricao) values('9','CELICA');
insert into marca_modelo (marca_id, descricao) values('9','COROLLA');
insert into marca_modelo (marca_id, descricao) values('9','CORONA');
insert into marca_modelo (marca_id, descricao) values('9','FIELDER');
insert into marca_modelo (marca_id, descricao) values('9','HILUX');
insert into marca_modelo (marca_id, descricao) values('10','POLO SEDAN');
insert into marca_modelo (marca_id, descricao) values('10','POLO');
insert into marca_modelo (marca_id, descricao) values('10','POINTER');
insert into marca_modelo (marca_id, descricao) values('10','PASSAT');
insert into marca_modelo (marca_id, descricao) values('10','PARATI');
insert into marca_modelo (marca_id, descricao) values('10','PAG NICK');
insert into marca_modelo (marca_id, descricao) values('10','NEW BEETLE');
insert into marca_modelo (marca_id, descricao) values('10','LOGUS');
insert into marca_modelo (marca_id, descricao) values('10','QUANTUM');
insert into marca_modelo (marca_id, descricao) values('10','SANTANA');
insert into marca_modelo (marca_id, descricao) values('10','SAVEIRO');
insert into marca_modelo (marca_id, descricao) values('10','VOYAGE');
insert into marca_modelo (marca_id, descricao) values('10','VARIANT II');
insert into marca_modelo (marca_id, descricao) values('10','VARIANT');
insert into marca_modelo (marca_id, descricao) values('10','VAN');
insert into marca_modelo (marca_id, descricao) values('10','TOUAREG');
insert into marca_modelo (marca_id, descricao) values('10','TL');
insert into marca_modelo (marca_id, descricao) values('10','SPACEFOX');
insert into marca_modelo (marca_id, descricao) values('10','SP');
insert into marca_modelo (marca_id, descricao) values('10','KOMBI');
insert into marca_modelo (marca_id, descricao) values('10','KARMANN-GHIA');
insert into marca_modelo (marca_id, descricao) values('10','BUGGY');
insert into marca_modelo (marca_id, descricao) values('10','BRASILIA');
insert into marca_modelo (marca_id, descricao) values('10','BORA');
insert into marca_modelo (marca_id, descricao) values('10','BIANCO');
insert into marca_modelo (marca_id, descricao) values('10','APOLLO');
insert into marca_modelo (marca_id, descricao) values('10','1600');
insert into marca_modelo (marca_id, descricao) values('10','1300');
insert into marca_modelo (marca_id, descricao) values('10','1200');
insert into marca_modelo (marca_id, descricao) values('10','BUGRE');
insert into marca_modelo (marca_id, descricao) values('10','CARAVELLE');
insert into marca_modelo (marca_id, descricao) values('10','CORRADO');
insert into marca_modelo (marca_id, descricao) values('10','JETTA III');
insert into marca_modelo (marca_id, descricao) values('10','GOLF');
insert into marca_modelo (marca_id, descricao) values('10','GOL');
insert into marca_modelo (marca_id, descricao) values('10','FUSCA');
insert into marca_modelo (marca_id, descricao) values('10','FOX');
insert into marca_modelo (marca_id, descricao) values('10','EUROVAN');
insert into marca_modelo (marca_id, descricao) values('10','CROSSFOX');
insert into marca_modelo (marca_id, descricao) values('10','COYOTE');
insert into marca_modelo (marca_id, descricao) values('12','NSX');
insert into marca_modelo (marca_id, descricao) values('12','LEGEND');
insert into marca_modelo (marca_id, descricao) values('12','INTEGRA');
insert into marca_modelo (marca_id, descricao) values('13','COUPÉ');
insert into marca_modelo (marca_id, descricao) values('14','FURGOVAN');
insert into marca_modelo (marca_id, descricao) values('14','MARRUÁ');
insert into marca_modelo (marca_id, descricao) values('15','2300 SL');
insert into marca_modelo (marca_id, descricao) values('15','2300 Ti');
insert into marca_modelo (marca_id, descricao) values('15','2300 Ti4');
insert into marca_modelo (marca_id, descricao) values('15','ALFETTA');
insert into marca_modelo (marca_id, descricao) values('15','GIULIETTA');
insert into marca_modelo (marca_id, descricao) values('15','SPIDER');
insert into marca_modelo (marca_id, descricao) values('15','2300 B');
insert into marca_modelo (marca_id, descricao) values('15','1750');
insert into marca_modelo (marca_id, descricao) values('15','145');
insert into marca_modelo (marca_id, descricao) values('15','147');
insert into marca_modelo (marca_id, descricao) values('15','155');
insert into marca_modelo (marca_id, descricao) values('15','156');
insert into marca_modelo (marca_id, descricao) values('15','164');
insert into marca_modelo (marca_id, descricao) values('15','166');
insert into marca_modelo (marca_id, descricao) values('16','CLASSIC 427');
insert into marca_modelo (marca_id, descricao) values('16','CLASSIC XK120');
insert into marca_modelo (marca_id, descricao) values('17','TOWNER');
insert into marca_modelo (marca_id, descricao) values('17','TOPIC');
insert into marca_modelo (marca_id, descricao) values('17','ROCSTA');
insert into marca_modelo (marca_id, descricao) values('17','HI-TOPIC');
insert into marca_modelo (marca_id, descricao) values('17','GALLOPER');
insert into marca_modelo (marca_id, descricao) values('17','AM 825');
insert into marca_modelo (marca_id, descricao) values('18','DB7');
insert into marca_modelo (marca_id, descricao) values('18','V8 VANTAGE ');
insert into marca_modelo (marca_id, descricao) values('19','RS2');
insert into marca_modelo (marca_id, descricao) values('19','RS4');
insert into marca_modelo (marca_id, descricao) values('19','RS6');
insert into marca_modelo (marca_id, descricao) values('19','S3');
insert into marca_modelo (marca_id, descricao) values('19','S4');
insert into marca_modelo (marca_id, descricao) values('19','S6');
insert into marca_modelo (marca_id, descricao) values('19','S8');
insert into marca_modelo (marca_id, descricao) values('19','TT');
insert into marca_modelo (marca_id, descricao) values('19','Q7');
insert into marca_modelo (marca_id, descricao) values('19','AVANT');
insert into marca_modelo (marca_id, descricao) values('19','100');
insert into marca_modelo (marca_id, descricao) values('19','80');
insert into marca_modelo (marca_id, descricao) values('19','A2');
insert into marca_modelo (marca_id, descricao) values('19','A3');
insert into marca_modelo (marca_id, descricao) values('19','A4');
insert into marca_modelo (marca_id, descricao) values('19','A6');
insert into marca_modelo (marca_id, descricao) values('19','A8');
insert into marca_modelo (marca_id, descricao) values('19','ALLROAD');
insert into marca_modelo (marca_id, descricao) values('20','A40');
insert into marca_modelo (marca_id, descricao) values('21','BUGGY');
insert into marca_modelo (marca_id, descricao) values('22','BABY TST');
insert into marca_modelo (marca_id, descricao) values('22','BABY');
insert into marca_modelo (marca_id, descricao) values('23','BROOKLANDS');
insert into marca_modelo (marca_id, descricao) values('23','CONTINENTAL');
insert into marca_modelo (marca_id, descricao) values('24','S');
insert into marca_modelo (marca_id, descricao) values('25','650Ci');
insert into marca_modelo (marca_id, descricao) values('25','650i');
insert into marca_modelo (marca_id, descricao) values('25','730i');
insert into marca_modelo (marca_id, descricao) values('25','730iA');
insert into marca_modelo (marca_id, descricao) values('25','735i');
insert into marca_modelo (marca_id, descricao) values('25','735IL E32 ');
insert into marca_modelo (marca_id, descricao) values('25','740i');
insert into marca_modelo (marca_id, descricao) values('25','650');
insert into marca_modelo (marca_id, descricao) values('25','645CI');
insert into marca_modelo (marca_id, descricao) values('25','635CSi');
insert into marca_modelo (marca_id, descricao) values('25','550i');
insert into marca_modelo (marca_id, descricao) values('25','545i');
insert into marca_modelo (marca_id, descricao) values('25','540iTA');
insert into marca_modelo (marca_id, descricao) values('25','540iA');
insert into marca_modelo (marca_id, descricao) values('25','540i');
insert into marca_modelo (marca_id, descricao) values('25','535i');
insert into marca_modelo (marca_id, descricao) values('25','740iL');
insert into marca_modelo (marca_id, descricao) values('25','745i');
insert into marca_modelo (marca_id, descricao) values('25','Z4');
insert into marca_modelo (marca_id, descricao) values('25','Z3');
insert into marca_modelo (marca_id, descricao) values('25','Z1');
insert into marca_modelo (marca_id, descricao) values('25','X5');
insert into marca_modelo (marca_id, descricao) values('25','X3');
insert into marca_modelo (marca_id, descricao) values('25','NEW CLASS');
insert into marca_modelo (marca_id, descricao) values('25','M6');
insert into marca_modelo (marca_id, descricao) values('25','M5');
insert into marca_modelo (marca_id, descricao) values('25','M3');
insert into marca_modelo (marca_id, descricao) values('25','ISETTA');
insert into marca_modelo (marca_id, descricao) values('25','850CSi');
insert into marca_modelo (marca_id, descricao) values('25','850Ci');
insert into marca_modelo (marca_id, descricao) values('25','840Ci');
insert into marca_modelo (marca_id, descricao) values('25','760Li');
insert into marca_modelo (marca_id, descricao) values('25','750i');
insert into marca_modelo (marca_id, descricao) values('25','Z8');
insert into marca_modelo (marca_id, descricao) values('25','530i');
insert into marca_modelo (marca_id, descricao) values('25','120i');
insert into marca_modelo (marca_id, descricao) values('25','323i');
insert into marca_modelo (marca_id, descricao) values('25','323CiA');
insert into marca_modelo (marca_id, descricao) values('25','323Ci');
insert into marca_modelo (marca_id, descricao) values('25','320i');
insert into marca_modelo (marca_id, descricao) values('25','318TiA');
insert into marca_modelo (marca_id, descricao) values('25','318Ti');
insert into marca_modelo (marca_id, descricao) values('25','318iSA');
insert into marca_modelo (marca_id, descricao) values('25','318iS');
insert into marca_modelo (marca_id, descricao) values('25','318i');
insert into marca_modelo (marca_id, descricao) values('25','316i');
insert into marca_modelo (marca_id, descricao) values('25','2002');
insert into marca_modelo (marca_id, descricao) values('25','1802');
insert into marca_modelo (marca_id, descricao) values('25','1602');
insert into marca_modelo (marca_id, descricao) values('25','1600');
insert into marca_modelo (marca_id, descricao) values('25','130i');
insert into marca_modelo (marca_id, descricao) values('25','323iA');
insert into marca_modelo (marca_id, descricao) values('25','323Ti');
insert into marca_modelo (marca_id, descricao) values('25','528iL');
insert into marca_modelo (marca_id, descricao) values('25','528iA');
insert into marca_modelo (marca_id, descricao) values('25','528i');
insert into marca_modelo (marca_id, descricao) values('25','525iA');
insert into marca_modelo (marca_id, descricao) values('25','525i');
insert into marca_modelo (marca_id, descricao) values('25','520i');
insert into marca_modelo (marca_id, descricao) values('25','335i');
insert into marca_modelo (marca_id, descricao) values('25','330iA');
insert into marca_modelo (marca_id, descricao) values('25','330i');
insert into marca_modelo (marca_id, descricao) values('25','325Ci');
insert into marca_modelo (marca_id, descricao) values('25','325i');
insert into marca_modelo (marca_id, descricao) values('25','325iA');
insert into marca_modelo (marca_id, descricao) values('25','328i');
insert into marca_modelo (marca_id, descricao) values('25','328iA');
insert into marca_modelo (marca_id, descricao) values('25','330Ci');
insert into marca_modelo (marca_id, descricao) values('25','330CiA');
insert into marca_modelo (marca_id, descricao) values('26','M-8');
insert into marca_modelo (marca_id, descricao) values('26','M-12');
insert into marca_modelo (marca_id, descricao) values('26','M-11');
insert into marca_modelo (marca_id, descricao) values('26','M-10 1/2');
insert into marca_modelo (marca_id, descricao) values('26','M-10');
insert into marca_modelo (marca_id, descricao) values('27','BUGGY');
insert into marca_modelo (marca_id, descricao) values('28','SPORTWAGON');
insert into marca_modelo (marca_id, descricao) values('28','ROADSTER');
insert into marca_modelo (marca_id, descricao) values('28','RIVIERA');
insert into marca_modelo (marca_id, descricao) values('28','REGAL');
insert into marca_modelo (marca_id, descricao) values('28','DINAFLOW');
insert into marca_modelo (marca_id, descricao) values('28','CENTURY');
insert into marca_modelo (marca_id, descricao) values('29','SRX');
insert into marca_modelo (marca_id, descricao) values('29','SEVILLE');
insert into marca_modelo (marca_id, descricao) values('29','LIMOUSINE');
insert into marca_modelo (marca_id, descricao) values('29','ESCALADE');
insert into marca_modelo (marca_id, descricao) values('29','ELDORADO');
insert into marca_modelo (marca_id, descricao) values('29','DE VILLE');
insert into marca_modelo (marca_id, descricao) values('29','BROUGHAM');
insert into marca_modelo (marca_id, descricao) values('30','JIPE JAVALI');
insert into marca_modelo (marca_id, descricao) values('31','SPEEDSTER');
insert into marca_modelo (marca_id, descricao) values('31','SPYDER');
insert into marca_modelo (marca_id, descricao) values('31','SUPER 90');
insert into marca_modelo (marca_id, descricao) values('32','UTILITY');
insert into marca_modelo (marca_id, descricao) values('32','FAMILY');
insert into marca_modelo (marca_id, descricao) values('32','CARGO X-CAB');
insert into marca_modelo (marca_id, descricao) values('32','CARGO');
insert into marca_modelo (marca_id, descricao) values('33','PACIFICA');
insert into marca_modelo (marca_id, descricao) values('33','PT CRUISER');
insert into marca_modelo (marca_id, descricao) values('33','SEBRING');
insert into marca_modelo (marca_id, descricao) values('33','STRATUS');
insert into marca_modelo (marca_id, descricao) values('33','TOWN & COUNTRY');
insert into marca_modelo (marca_id, descricao) values('33','VISION');
insert into marca_modelo (marca_id, descricao) values('33','VOYAGER');
insert into marca_modelo (marca_id, descricao) values('33','NEON');
insert into marca_modelo (marca_id, descricao) values('33','LE BARON');
insert into marca_modelo (marca_id, descricao) values('33','300 C');
insert into marca_modelo (marca_id, descricao) values('33','300 M');
insert into marca_modelo (marca_id, descricao) values('33','CARAVAN');
insert into marca_modelo (marca_id, descricao) values('33','CIRRUS');
insert into marca_modelo (marca_id, descricao) values('33','CONCORDE');
insert into marca_modelo (marca_id, descricao) values('33','DE SOTO');
insert into marca_modelo (marca_id, descricao) values('33','GRAND CARAVAN');
insert into marca_modelo (marca_id, descricao) values('34','RÉPLICA');
insert into marca_modelo (marca_id, descricao) values('35','CL');
insert into marca_modelo (marca_id, descricao) values('36','TICO');
insert into marca_modelo (marca_id, descricao) values('36','SUPER SALON');
insert into marca_modelo (marca_id, descricao) values('36','RACER');
insert into marca_modelo (marca_id, descricao) values('36','PRINCE');
insert into marca_modelo (marca_id, descricao) values('36','NUBIRA');
insert into marca_modelo (marca_id, descricao) values('36','LEGANZA');
insert into marca_modelo (marca_id, descricao) values('36','LANOS');
insert into marca_modelo (marca_id, descricao) values('36','ESPERO');
insert into marca_modelo (marca_id, descricao) values('37','TERIOS');
insert into marca_modelo (marca_id, descricao) values('37','APPLAUSE');
insert into marca_modelo (marca_id, descricao) values('37','CHARADE');
insert into marca_modelo (marca_id, descricao) values('37','CUORE');
insert into marca_modelo (marca_id, descricao) values('37','FEROZA');
insert into marca_modelo (marca_id, descricao) values('37','GRAN MOVE');
insert into marca_modelo (marca_id, descricao) values('37','MOVE VAN');
insert into marca_modelo (marca_id, descricao) values('38','VEMAGUET');
insert into marca_modelo (marca_id, descricao) values('38','FISSORE');
insert into marca_modelo (marca_id, descricao) values('38','CANDANGO');
insert into marca_modelo (marca_id, descricao) values('38','BELCAR');
insert into marca_modelo (marca_id, descricao) values('39','VIPER');
insert into marca_modelo (marca_id, descricao) values('39','STEALTH');
insert into marca_modelo (marca_id, descricao) values('39','RAM');
insert into marca_modelo (marca_id, descricao) values('39','POLARA');
insert into marca_modelo (marca_id, descricao) values('39','MAGNUM');
insert into marca_modelo (marca_id, descricao) values('39','LE BARON');
insert into marca_modelo (marca_id, descricao) values('39','INTREPID');
insert into marca_modelo (marca_id, descricao) values('39','DURANGO');
insert into marca_modelo (marca_id, descricao) values('39','DART');
insert into marca_modelo (marca_id, descricao) values('39','DAKOTA');
insert into marca_modelo (marca_id, descricao) values('39','CHARGER');
insert into marca_modelo (marca_id, descricao) values('39','AVENGER');
insert into marca_modelo (marca_id, descricao) values('40','BUGUE');
insert into marca_modelo (marca_id, descricao) values('41','FURGÃO');
insert into marca_modelo (marca_id, descricao) values('41','M100');
insert into marca_modelo (marca_id, descricao) values('41','MINIVAN');
insert into marca_modelo (marca_id, descricao) values('41','VAN PICKUP');
insert into marca_modelo (marca_id, descricao) values('42','ENGESA');
insert into marca_modelo (marca_id, descricao) values('43','SUPER 90');
insert into marca_modelo (marca_id, descricao) values('43','ENVEMO');
insert into marca_modelo (marca_id, descricao) values('43','CAMPER');
insert into marca_modelo (marca_id, descricao) values('45','F550');
insert into marca_modelo (marca_id, descricao) values('45','F512 M');
insert into marca_modelo (marca_id, descricao) values('45','F50');
insert into marca_modelo (marca_id, descricao) values('45','F456 M');
insert into marca_modelo (marca_id, descricao) values('45','F456');
insert into marca_modelo (marca_id, descricao) values('45','F430');
insert into marca_modelo (marca_id, descricao) values('45','F40');
insert into marca_modelo (marca_id, descricao) values('45','F360');
insert into marca_modelo (marca_id, descricao) values('45','F355 F1');
insert into marca_modelo (marca_id, descricao) values('45','F355');
insert into marca_modelo (marca_id, descricao) values('45','DINO 308');
insert into marca_modelo (marca_id, descricao) values('45','DINO 246 GT');
insert into marca_modelo (marca_id, descricao) values('45','612');
insert into marca_modelo (marca_id, descricao) values('45','348');
insert into marca_modelo (marca_id, descricao) values('45','F575M');
insert into marca_modelo (marca_id, descricao) values('46','2000');
insert into marca_modelo (marca_id, descricao) values('48','METRO');
insert into marca_modelo (marca_id, descricao) values('48','STORM');
insert into marca_modelo (marca_id, descricao) values('49','YUKON');
insert into marca_modelo (marca_id, descricao) values('49','SS');
insert into marca_modelo (marca_id, descricao) values('49','SONOMA');
insert into marca_modelo (marca_id, descricao) values('49','SILVERADO');
insert into marca_modelo (marca_id, descricao) values('49','SIERRA');
insert into marca_modelo (marca_id, descricao) values('49','ENVOY');
insert into marca_modelo (marca_id, descricao) values('49','CHEYENNE');
insert into marca_modelo (marca_id, descricao) values('49','BLAZER');
insert into marca_modelo (marca_id, descricao) values('49','3500 HD');
insert into marca_modelo (marca_id, descricao) values('50','FUTURA');
insert into marca_modelo (marca_id, descricao) values('51','XEF');
insert into marca_modelo (marca_id, descricao) values('51','XAVANTE');
insert into marca_modelo (marca_id, descricao) values('51','X12');
insert into marca_modelo (marca_id, descricao) values('51','SUPERMINI ');
insert into marca_modelo (marca_id, descricao) values('51','G800');
insert into marca_modelo (marca_id, descricao) values('51','G-15');
insert into marca_modelo (marca_id, descricao) values('51','CARAJÁS');
insert into marca_modelo (marca_id, descricao) values('51','BR-800');
insert into marca_modelo (marca_id, descricao) values('52','H3');
insert into marca_modelo (marca_id, descricao) values('52','H2');
insert into marca_modelo (marca_id, descricao) values('52','AM');
insert into marca_modelo (marca_id, descricao) values('53','SANTA FÉ');
insert into marca_modelo (marca_id, descricao) values('53','SCOUPE');
insert into marca_modelo (marca_id, descricao) values('53','SONATA');
insert into marca_modelo (marca_id, descricao) values('53','TERRACAN');
insert into marca_modelo (marca_id, descricao) values('53','TIBURON');
insert into marca_modelo (marca_id, descricao) values('53','TRAJET');
insert into marca_modelo (marca_id, descricao) values('53','TUCSON');
insert into marca_modelo (marca_id, descricao) values('53','VERA CRUZ');
insert into marca_modelo (marca_id, descricao) values('53','PORTER');
insert into marca_modelo (marca_id, descricao) values('53','MATRIX');
insert into marca_modelo (marca_id, descricao) values('53','HR ');
insert into marca_modelo (marca_id, descricao) values('53','ACCENT');
insert into marca_modelo (marca_id, descricao) values('53','ATOS');
insert into marca_modelo (marca_id, descricao) values('53','COUPÊ');
insert into marca_modelo (marca_id, descricao) values('53','ELANTRA');
insert into marca_modelo (marca_id, descricao) values('53','EXCEL');
insert into marca_modelo (marca_id, descricao) values('53','GALLOPER');
insert into marca_modelo (marca_id, descricao) values('53','H1 STAREX');
insert into marca_modelo (marca_id, descricao) values('53','H100');
insert into marca_modelo (marca_id, descricao) values('54','Q45');
insert into marca_modelo (marca_id, descricao) values('54','J30');
insert into marca_modelo (marca_id, descricao) values('54','G35 ');
insert into marca_modelo (marca_id, descricao) values('54','FX45');
insert into marca_modelo (marca_id, descricao) values('54','FX35');
insert into marca_modelo (marca_id, descricao) values('56','AMIGO');
insert into marca_modelo (marca_id, descricao) values('56','HOMBRE');
insert into marca_modelo (marca_id, descricao) values('56','IMPULSE');
insert into marca_modelo (marca_id, descricao) values('56','RODEO');
insert into marca_modelo (marca_id, descricao) values('56','TROOPER');
insert into marca_modelo (marca_id, descricao) values('57','DAILY 50.13');
insert into marca_modelo (marca_id, descricao) values('57','DAILY');
insert into marca_modelo (marca_id, descricao) values('57','5912');
insert into marca_modelo (marca_id, descricao) values('58','XJ6');
insert into marca_modelo (marca_id, descricao) values('58','XJ8');
insert into marca_modelo (marca_id, descricao) values('58','XJR');
insert into marca_modelo (marca_id, descricao) values('58','XJS');
insert into marca_modelo (marca_id, descricao) values('58','XK');
insert into marca_modelo (marca_id, descricao) values('58','XK 120');
insert into marca_modelo (marca_id, descricao) values('58','XK8');
insert into marca_modelo (marca_id, descricao) values('58','XK8 AUTO');
insert into marca_modelo (marca_id, descricao) values('58','XKR');
insert into marca_modelo (marca_id, descricao) values('58','XJ12L');
insert into marca_modelo (marca_id, descricao) values('58','XJ12');
insert into marca_modelo (marca_id, descricao) values('58','DAIMLER');
insert into marca_modelo (marca_id, descricao) values('58','DAIMLER LONG');
insert into marca_modelo (marca_id, descricao) values('58','EXECUTIVE');
insert into marca_modelo (marca_id, descricao) values('58','LISTER');
insert into marca_modelo (marca_id, descricao) values('58','S-TYPE');
insert into marca_modelo (marca_id, descricao) values('58','SOVEREIGN LONG');
insert into marca_modelo (marca_id, descricao) values('58','X-TYPE');
insert into marca_modelo (marca_id, descricao) values('58','XJ');
insert into marca_modelo (marca_id, descricao) values('58','XJ-S');
insert into marca_modelo (marca_id, descricao) values('59','WRANGLER');
insert into marca_modelo (marca_id, descricao) values('59','LIBERTY');
insert into marca_modelo (marca_id, descricao) values('59','GRAND CHEROKEE');
insert into marca_modelo (marca_id, descricao) values('59','COMMANDER');
insert into marca_modelo (marca_id, descricao) values('59','CJ 5');
insert into marca_modelo (marca_id, descricao) values('59','CHEROKEE');
insert into marca_modelo (marca_id, descricao) values('60','MONTEZ');
insert into marca_modelo (marca_id, descricao) values('61','OPIRUS');
insert into marca_modelo (marca_id, descricao) values('61','PICANTO');
insert into marca_modelo (marca_id, descricao) values('61','SEPHIA');
insert into marca_modelo (marca_id, descricao) values('61','SHUMA');
insert into marca_modelo (marca_id, descricao) values('61','SORENTO');
insert into marca_modelo (marca_id, descricao) values('61','SPORTAGE');
insert into marca_modelo (marca_id, descricao) values('61','MAGENTIS');
insert into marca_modelo (marca_id, descricao) values('61','CLARUS');
insert into marca_modelo (marca_id, descricao) values('61','CERES');
insert into marca_modelo (marca_id, descricao) values('61','Cerato');
insert into marca_modelo (marca_id, descricao) values('61','CARNIVAL');
insert into marca_modelo (marca_id, descricao) values('61','CARENS');
insert into marca_modelo (marca_id, descricao) values('61','BONGO');
insert into marca_modelo (marca_id, descricao) values('61','BESTA');
insert into marca_modelo (marca_id, descricao) values('62','SAMARA');
insert into marca_modelo (marca_id, descricao) values('62','NIVA');
insert into marca_modelo (marca_id, descricao) values('62','LAIKA');
insert into marca_modelo (marca_id, descricao) values('63','DIABLO');
insert into marca_modelo (marca_id, descricao) values('63','GALLARDO');
insert into marca_modelo (marca_id, descricao) values('63','MURCIELAGO');
insert into marca_modelo (marca_id, descricao) values('64','DELTA');
insert into marca_modelo (marca_id, descricao) values('65','RANGE ROVER SPORT');
insert into marca_modelo (marca_id, descricao) values('65','RANGE ROVER');
insert into marca_modelo (marca_id, descricao) values('65','FREELANDER');
insert into marca_modelo (marca_id, descricao) values('65','DISCOVERY 3');
insert into marca_modelo (marca_id, descricao) values('65','DISCOVERY 2');
insert into marca_modelo (marca_id, descricao) values('65','DISCOVERY');
insert into marca_modelo (marca_id, descricao) values('65','DEFENDER');
insert into marca_modelo (marca_id, descricao) values('66','SC 430');
insert into marca_modelo (marca_id, descricao) values('66','SC 400');
insert into marca_modelo (marca_id, descricao) values('66','SC 300');
insert into marca_modelo (marca_id, descricao) values('66','RX 350');
insert into marca_modelo (marca_id, descricao) values('66','RX');
insert into marca_modelo (marca_id, descricao) values('66','LS 400');
insert into marca_modelo (marca_id, descricao) values('66','LS');
insert into marca_modelo (marca_id, descricao) values('66','GS');
insert into marca_modelo (marca_id, descricao) values('66','ES 350');
insert into marca_modelo (marca_id, descricao) values('66','ES');
insert into marca_modelo (marca_id, descricao) values('67','TOWN CAR');
insert into marca_modelo (marca_id, descricao) values('67','NAVIGATOR');
insert into marca_modelo (marca_id, descricao) values('67','MARK VIII');
insert into marca_modelo (marca_id, descricao) values('67','LS');
insert into marca_modelo (marca_id, descricao) values('67','CONTINENTAL');
insert into marca_modelo (marca_id, descricao) values('68','H1');
insert into marca_modelo (marca_id, descricao) values('69','ELAN');
insert into marca_modelo (marca_id, descricao) values('69','ELISE');
insert into marca_modelo (marca_id, descricao) values('69','ESPIRIT');
insert into marca_modelo (marca_id, descricao) values('69','EXIGE');
insert into marca_modelo (marca_id, descricao) values('70','VOLARE');
insert into marca_modelo (marca_id, descricao) values('70','FRATELLO');
insert into marca_modelo (marca_id, descricao) values('71','BEACH');
insert into marca_modelo (marca_id, descricao) values('71','SUPER');
insert into marca_modelo (marca_id, descricao) values('72','SPYDER');
insert into marca_modelo (marca_id, descricao) values('72','SHAMAL');
insert into marca_modelo (marca_id, descricao) values('72','QUATTROPORTE');
insert into marca_modelo (marca_id, descricao) values('72','GRANSPORT');
insert into marca_modelo (marca_id, descricao) values('72','GHIBLI');
insert into marca_modelo (marca_id, descricao) values('72','COUPÉ');
insert into marca_modelo (marca_id, descricao) values('72','430');
insert into marca_modelo (marca_id, descricao) values('72','4200');
insert into marca_modelo (marca_id, descricao) values('72','3200');
insert into marca_modelo (marca_id, descricao) values('72','222');
insert into marca_modelo (marca_id, descricao) values('73','PICK-UP');
insert into marca_modelo (marca_id, descricao) values('74','MX-5/MIATA');
insert into marca_modelo (marca_id, descricao) values('74','MX-6');
insert into marca_modelo (marca_id, descricao) values('74','NAVAJO');
insert into marca_modelo (marca_id, descricao) values('74','PROTEGÉ');
insert into marca_modelo (marca_id, descricao) values('74','RX-7');
insert into marca_modelo (marca_id, descricao) values('74','RX-8');
insert into marca_modelo (marca_id, descricao) values('74','XEDOS-9');
insert into marca_modelo (marca_id, descricao) values('74','MX-3');
insert into marca_modelo (marca_id, descricao) values('74','MX');
insert into marca_modelo (marca_id, descricao) values('74','323');
insert into marca_modelo (marca_id, descricao) values('74','626');
insert into marca_modelo (marca_id, descricao) values('74','929');
insert into marca_modelo (marca_id, descricao) values('74','B-2200');
insert into marca_modelo (marca_id, descricao) values('74','B-2500');
insert into marca_modelo (marca_id, descricao) values('74','MILLENIA');
insert into marca_modelo (marca_id, descricao) values('74','MPV');
insert into marca_modelo (marca_id, descricao) values('75','E 500 EB4');
insert into marca_modelo (marca_id, descricao) values('75','E 500');
insert into marca_modelo (marca_id, descricao) values('75','E 430');
insert into marca_modelo (marca_id, descricao) values('75','E 420');
insert into marca_modelo (marca_id, descricao) values('75','E 350');
insert into marca_modelo (marca_id, descricao) values('75','E 320');
insert into marca_modelo (marca_id, descricao) values('75','E 240');
insert into marca_modelo (marca_id, descricao) values('75','E 55 AMG');
insert into marca_modelo (marca_id, descricao) values('75','E 55 K AMG');
insert into marca_modelo (marca_id, descricao) values('75','E 55 T AMG');
insert into marca_modelo (marca_id, descricao) values('75','E 65');
insert into marca_modelo (marca_id, descricao) values('75','G 350 TD');
insert into marca_modelo (marca_id, descricao) values('75','G 400 ');
insert into marca_modelo (marca_id, descricao) values('75','G 400 CDI SW 2850');
insert into marca_modelo (marca_id, descricao) values('75','G 500');
insert into marca_modelo (marca_id, descricao) values('75','G 500 SW 2850');
insert into marca_modelo (marca_id, descricao) values('75','E 220');
insert into marca_modelo (marca_id, descricao) values('75','E 200');
insert into marca_modelo (marca_id, descricao) values('75','CLASSE A');
insert into marca_modelo (marca_id, descricao) values('75','CLK');
insert into marca_modelo (marca_id, descricao) values('75','CLK 230');
insert into marca_modelo (marca_id, descricao) values('75','CLK 320');
insert into marca_modelo (marca_id, descricao) values('75','CLK 350');
insert into marca_modelo (marca_id, descricao) values('75','CLK 350 CA');
insert into marca_modelo (marca_id, descricao) values('75','CLK 430');
insert into marca_modelo (marca_id, descricao) values('75','CLK 500');
insert into marca_modelo (marca_id, descricao) values('75','CLK 500 CA');
insert into marca_modelo (marca_id, descricao) values('75','CLK 55 AMG');
insert into marca_modelo (marca_id, descricao) values('75','CLK 55 AMG CA');
insert into marca_modelo (marca_id, descricao) values('75','CLS 350');
insert into marca_modelo (marca_id, descricao) values('75','CLS 500');
insert into marca_modelo (marca_id, descricao) values('75','CLS 55 AMG');
insert into marca_modelo (marca_id, descricao) values('75','CLS 63 AMG');
insert into marca_modelo (marca_id, descricao) values('75','CL 65');
insert into marca_modelo (marca_id, descricao) values('75','G 55 AMG SW 2850');
insert into marca_modelo (marca_id, descricao) values('75','MICROÔNIBUS');
insert into marca_modelo (marca_id, descricao) values('75','S 600');
insert into marca_modelo (marca_id, descricao) values('75','SL 280');
insert into marca_modelo (marca_id, descricao) values('75','SL 320');
insert into marca_modelo (marca_id, descricao) values('75','SL 350');
insert into marca_modelo (marca_id, descricao) values('75','SL 500');
insert into marca_modelo (marca_id, descricao) values('75','SL 55 AMG');
insert into marca_modelo (marca_id, descricao) values('75','SL 55 K AMG');
insert into marca_modelo (marca_id, descricao) values('75','SL 600');
insert into marca_modelo (marca_id, descricao) values('75','SL 65 AMG');
insert into marca_modelo (marca_id, descricao) values('75','SLK 200');
insert into marca_modelo (marca_id, descricao) values('75','SLK 230');
insert into marca_modelo (marca_id, descricao) values('75','SLK 320');
insert into marca_modelo (marca_id, descricao) values('75','SLK 350');
insert into marca_modelo (marca_id, descricao) values('75','SLK 55 AMG');
insert into marca_modelo (marca_id, descricao) values('75','SMART');
insert into marca_modelo (marca_id, descricao) values('75','S 55');
insert into marca_modelo (marca_id, descricao) values('75','S 500 L');
insert into marca_modelo (marca_id, descricao) values('75','ML');
insert into marca_modelo (marca_id, descricao) values('75','ML 230');
insert into marca_modelo (marca_id, descricao) values('75','ML 320');
insert into marca_modelo (marca_id, descricao) values('75','ML 350');
insert into marca_modelo (marca_id, descricao) values('75','ML 430');
insert into marca_modelo (marca_id, descricao) values('75','ML 500');
insert into marca_modelo (marca_id, descricao) values('75','ML 55 AMG');
insert into marca_modelo (marca_id, descricao) values('75','R 500');
insert into marca_modelo (marca_id, descricao) values('75','R 500 L');
insert into marca_modelo (marca_id, descricao) values('75','R 63 AMG');
insert into marca_modelo (marca_id, descricao) values('75','R 63 L AMG');
insert into marca_modelo (marca_id, descricao) values('75','S 280');
insert into marca_modelo (marca_id, descricao) values('75','S 320');
insert into marca_modelo (marca_id, descricao) values('75','S 420');
insert into marca_modelo (marca_id, descricao) values('75','S 500');
insert into marca_modelo (marca_id, descricao) values('75','SPRINTER');
insert into marca_modelo (marca_id, descricao) values('75','170 D');
insert into marca_modelo (marca_id, descricao) values('75','280 CE');
insert into marca_modelo (marca_id, descricao) values('75','280 E');
insert into marca_modelo (marca_id, descricao) values('75','280 S');
insert into marca_modelo (marca_id, descricao) values('75','280 SE');
insert into marca_modelo (marca_id, descricao) values('75','280 SEL');
insert into marca_modelo (marca_id, descricao) values('75','280 SL');
insert into marca_modelo (marca_id, descricao) values('75','280 TE SW');
insert into marca_modelo (marca_id, descricao) values('75','300 CE');
insert into marca_modelo (marca_id, descricao) values('75','300 D');
insert into marca_modelo (marca_id, descricao) values('75','300 E');
insert into marca_modelo (marca_id, descricao) values('75','300 SE');
insert into marca_modelo (marca_id, descricao) values('75','300 SEL');
insert into marca_modelo (marca_id, descricao) values('75','300 SL');
insert into marca_modelo (marca_id, descricao) values('75','300 TD');
insert into marca_modelo (marca_id, descricao) values('75','300 TE');
insert into marca_modelo (marca_id, descricao) values('75','280 C');
insert into marca_modelo (marca_id, descricao) values('75','260 E');
insert into marca_modelo (marca_id, descricao) values('75','180 D');
insert into marca_modelo (marca_id, descricao) values('75','190 D');
insert into marca_modelo (marca_id, descricao) values('75','190 E');
insert into marca_modelo (marca_id, descricao) values('75','200 B');
insert into marca_modelo (marca_id, descricao) values('75','200 D');
insert into marca_modelo (marca_id, descricao) values('75','220 C');
insert into marca_modelo (marca_id, descricao) values('75','220 D');
insert into marca_modelo (marca_id, descricao) values('75','220 E');
insert into marca_modelo (marca_id, descricao) values('75','220 S');
insert into marca_modelo (marca_id, descricao) values('75','230 E');
insert into marca_modelo (marca_id, descricao) values('75','230 S');
insert into marca_modelo (marca_id, descricao) values('75','230.4');
insert into marca_modelo (marca_id, descricao) values('75','230.6');
insert into marca_modelo (marca_id, descricao) values('75','240 D');
insert into marca_modelo (marca_id, descricao) values('75','250 CE');
insert into marca_modelo (marca_id, descricao) values('75','313');
insert into marca_modelo (marca_id, descricao) values('75','320 E');
insert into marca_modelo (marca_id, descricao) values('75','CL 600');
insert into marca_modelo (marca_id, descricao) values('75','C 180 K');
insert into marca_modelo (marca_id, descricao) values('75','C 200');
insert into marca_modelo (marca_id, descricao) values('75','C 200 K');
insert into marca_modelo (marca_id, descricao) values('75','C 220');
insert into marca_modelo (marca_id, descricao) values('75','C 230');
insert into marca_modelo (marca_id, descricao) values('75','C 240');
insert into marca_modelo (marca_id, descricao) values('75','C 280');
insert into marca_modelo (marca_id, descricao) values('75','C 32 AMG');
insert into marca_modelo (marca_id, descricao) values('75','C 320');
insert into marca_modelo (marca_id, descricao) values('75','C 350');
insert into marca_modelo (marca_id, descricao) values('75','C 36 AMG');
insert into marca_modelo (marca_id, descricao) values('75','C 43 AMG');
insert into marca_modelo (marca_id, descricao) values('75','C 55 AMG');
insert into marca_modelo (marca_id, descricao) values('75','C 55 TAMG');
insert into marca_modelo (marca_id, descricao) values('75','CL 500');
insert into marca_modelo (marca_id, descricao) values('75','C 180');
insert into marca_modelo (marca_id, descricao) values('75','B 200');
insert into marca_modelo (marca_id, descricao) values('75','320 SL');
insert into marca_modelo (marca_id, descricao) values('75','350 SE');
insert into marca_modelo (marca_id, descricao) values('75','350 SEL');
insert into marca_modelo (marca_id, descricao) values('75','350 SL');
insert into marca_modelo (marca_id, descricao) values('75','450 SE');
insert into marca_modelo (marca_id, descricao) values('75','450 SEL');
insert into marca_modelo (marca_id, descricao) values('75','450 SL');
insert into marca_modelo (marca_id, descricao) values('75','450 SLC');
insert into marca_modelo (marca_id, descricao) values('75','500 E');
insert into marca_modelo (marca_id, descricao) values('75','600 SL');
insert into marca_modelo (marca_id, descricao) values('75','560 SEL');
insert into marca_modelo (marca_id, descricao) values('75','560 SEC');
insert into marca_modelo (marca_id, descricao) values('75','500 SL');
insert into marca_modelo (marca_id, descricao) values('75','500 SEL');
insert into marca_modelo (marca_id, descricao) values('75','500 SEC');
insert into marca_modelo (marca_id, descricao) values('75','500 SE');
insert into marca_modelo (marca_id, descricao) values('76','VILLAGER');
insert into marca_modelo (marca_id, descricao) values('76','SABLE');
insert into marca_modelo (marca_id, descricao) values('76','MYSTIQUE');
insert into marca_modelo (marca_id, descricao) values('76','COUGAR');
insert into marca_modelo (marca_id, descricao) values('77','MGB');
insert into marca_modelo (marca_id, descricao) values('77','TC');
insert into marca_modelo (marca_id, descricao) values('78','MORRIS');
insert into marca_modelo (marca_id, descricao) values('78','COOPER');
insert into marca_modelo (marca_id, descricao) values('79','X8');
insert into marca_modelo (marca_id, descricao) values('79','TOP SPORT');
insert into marca_modelo (marca_id, descricao) values('79','TARGA');
insert into marca_modelo (marca_id, descricao) values('79','SPORT');
insert into marca_modelo (marca_id, descricao) values('79','SAGA');
insert into marca_modelo (marca_id, descricao) values('79','MTS');
insert into marca_modelo (marca_id, descricao) values('79','CABRIOLET');
insert into marca_modelo (marca_id, descricao) values('79','BG');
insert into marca_modelo (marca_id, descricao) values('80','MINI');
insert into marca_modelo (marca_id, descricao) values('81','CLASSICO');
insert into marca_modelo (marca_id, descricao) values('81','TI');
insert into marca_modelo (marca_id, descricao) values('82','NX');
insert into marca_modelo (marca_id, descricao) values('82','PATHFINDER');
insert into marca_modelo (marca_id, descricao) values('82','PICK-UP');
insert into marca_modelo (marca_id, descricao) values('82','PRIMERA');
insert into marca_modelo (marca_id, descricao) values('82','QUEST');
insert into marca_modelo (marca_id, descricao) values('82','SENTRA');
insert into marca_modelo (marca_id, descricao) values('82','STANZA');
insert into marca_modelo (marca_id, descricao) values('82','TERRANO');
insert into marca_modelo (marca_id, descricao) values('82','TIIDA');
insert into marca_modelo (marca_id, descricao) values('82','VAN');
insert into marca_modelo (marca_id, descricao) values('82','X-TRAIL ');
insert into marca_modelo (marca_id, descricao) values('82','XTERRA');
insert into marca_modelo (marca_id, descricao) values('82','MURANO');
insert into marca_modelo (marca_id, descricao) values('82','MICRA');
insert into marca_modelo (marca_id, descricao) values('82','MAXIMA');
insert into marca_modelo (marca_id, descricao) values('82','240SX');
insert into marca_modelo (marca_id, descricao) values('82','300 ZX');
insert into marca_modelo (marca_id, descricao) values('82','350Z');
insert into marca_modelo (marca_id, descricao) values('82','ALTIMA');
insert into marca_modelo (marca_id, descricao) values('82','ARMADA');
insert into marca_modelo (marca_id, descricao) values('82','AX');
insert into marca_modelo (marca_id, descricao) values('82','D');
insert into marca_modelo (marca_id, descricao) values('82','D21');
insert into marca_modelo (marca_id, descricao) values('82','FRONTIER');
insert into marca_modelo (marca_id, descricao) values('82','INFINITI');
insert into marca_modelo (marca_id, descricao) values('82','J30');
insert into marca_modelo (marca_id, descricao) values('82','KING CAB');
insert into marca_modelo (marca_id, descricao) values('83','F-85 CUTLASS');
insert into marca_modelo (marca_id, descricao) values('83','ACHIEVA');
insert into marca_modelo (marca_id, descricao) values('84','RECORD');
insert into marca_modelo (marca_id, descricao) values('85','GRAND VOYAGER');
insert into marca_modelo (marca_id, descricao) values('86','TRANS SPORT');
insert into marca_modelo (marca_id, descricao) values('86','SOLSTICE');
insert into marca_modelo (marca_id, descricao) values('86','GTO');
insert into marca_modelo (marca_id, descricao) values('86','FORMULA 402');
insert into marca_modelo (marca_id, descricao) values('86','FORMULA 401');
insert into marca_modelo (marca_id, descricao) values('86','FORMULA 400');
insert into marca_modelo (marca_id, descricao) values('86','FIREBIRD');
insert into marca_modelo (marca_id, descricao) values('86','FIERO');
insert into marca_modelo (marca_id, descricao) values('87','968');
insert into marca_modelo (marca_id, descricao) values('87','BOXSTER');
insert into marca_modelo (marca_id, descricao) values('87','BOXSTER S');
insert into marca_modelo (marca_id, descricao) values('87','CARRERA');
insert into marca_modelo (marca_id, descricao) values('87','CAYENNE');
insert into marca_modelo (marca_id, descricao) values('87','CAYMAN');
insert into marca_modelo (marca_id, descricao) values('87','CAYMAN S');
insert into marca_modelo (marca_id, descricao) values('87','KREMER');
insert into marca_modelo (marca_id, descricao) values('87','SPYDER 500');
insert into marca_modelo (marca_id, descricao) values('87','SPYDER 550');
insert into marca_modelo (marca_id, descricao) values('87','944');
insert into marca_modelo (marca_id, descricao) values('87','928');
insert into marca_modelo (marca_id, descricao) values('87','911T');
insert into marca_modelo (marca_id, descricao) values('87','911');
insert into marca_modelo (marca_id, descricao) values('87','914');
insert into marca_modelo (marca_id, descricao) values('88','GTC');
insert into marca_modelo (marca_id, descricao) values('88','P-018S');
insert into marca_modelo (marca_id, descricao) values('88','GTS');
insert into marca_modelo (marca_id, descricao) values('88','GTE');
insert into marca_modelo (marca_id, descricao) values('88','GTB/S2');
insert into marca_modelo (marca_id, descricao) values('88','GTB');
insert into marca_modelo (marca_id, descricao) values('88','GT');
insert into marca_modelo (marca_id, descricao) values('88','AMV');
insert into marca_modelo (marca_id, descricao) values('89','SILVER SPUR');
insert into marca_modelo (marca_id, descricao) values('89','SILVER SHADOW');
insert into marca_modelo (marca_id, descricao) values('90','ROMI-ISETTA');
insert into marca_modelo (marca_id, descricao) values('91','Streetwise');
insert into marca_modelo (marca_id, descricao) values('91','série 800');
insert into marca_modelo (marca_id, descricao) values('91','série 600');
insert into marca_modelo (marca_id, descricao) values('91','série 400');
insert into marca_modelo (marca_id, descricao) values('91','série 200');
insert into marca_modelo (marca_id, descricao) values('91','série 100');
insert into marca_modelo (marca_id, descricao) values('91','75');
insert into marca_modelo (marca_id, descricao) values('91','45');
insert into marca_modelo (marca_id, descricao) values('91','25');
insert into marca_modelo (marca_id, descricao) values('92','9000');
insert into marca_modelo (marca_id, descricao) values('92','900');
insert into marca_modelo (marca_id, descricao) values('92','9-5');
insert into marca_modelo (marca_id, descricao) values('92','9-3');
insert into marca_modelo (marca_id, descricao) values('93','SM 4.1');
insert into marca_modelo (marca_id, descricao) values('94','SL-2');
insert into marca_modelo (marca_id, descricao) values('95','Toledo');
insert into marca_modelo (marca_id, descricao) values('95','Terra');
insert into marca_modelo (marca_id, descricao) values('95','Marbella');
insert into marca_modelo (marca_id, descricao) values('95','Málaga');
insert into marca_modelo (marca_id, descricao) values('95','Leon');
insert into marca_modelo (marca_id, descricao) values('95','Inca');
insert into marca_modelo (marca_id, descricao) values('95','Ibiza');
insert into marca_modelo (marca_id, descricao) values('95','Cordoba');
insert into marca_modelo (marca_id, descricao) values('95','Arosa');
insert into marca_modelo (marca_id, descricao) values('95','Altea');
insert into marca_modelo (marca_id, descricao) values('95','Alhambra');
insert into marca_modelo (marca_id, descricao) values('96','MUSTANG');
insert into marca_modelo (marca_id, descricao) values('96','COBRA');
insert into marca_modelo (marca_id, descricao) values('97','TURBO EX');
insert into marca_modelo (marca_id, descricao) values('98','CHAMBORD');
insert into marca_modelo (marca_id, descricao) values('99','Roadster Coupé');
insert into marca_modelo (marca_id, descricao) values('99','Roadster');
insert into marca_modelo (marca_id, descricao) values('99','Fortwo');
insert into marca_modelo (marca_id, descricao) values('99','Forfour');
insert into marca_modelo (marca_id, descricao) values('99','Crossblade');
insert into marca_modelo (marca_id, descricao) values('100','REXTON II');
insert into marca_modelo (marca_id, descricao) values('100','REXTON');
insert into marca_modelo (marca_id, descricao) values('100','MUSSO');
insert into marca_modelo (marca_id, descricao) values('100','KYRON');
insert into marca_modelo (marca_id, descricao) values('100','KORANDO');
insert into marca_modelo (marca_id, descricao) values('100','ISTANA');
insert into marca_modelo (marca_id, descricao) values('100','CHAIRMAN');
insert into marca_modelo (marca_id, descricao) values('100','ACTYON SPORTS');
insert into marca_modelo (marca_id, descricao) values('100','ACTYON');
insert into marca_modelo (marca_id, descricao) values('101','STUDEBAKER PICK-UP');
insert into marca_modelo (marca_id, descricao) values('102','VIVIO');
insert into marca_modelo (marca_id, descricao) values('102','TRIBECA');
insert into marca_modelo (marca_id, descricao) values('102','SVX');
insert into marca_modelo (marca_id, descricao) values('102','OUTBACK');
insert into marca_modelo (marca_id, descricao) values('102','LEGACY');
insert into marca_modelo (marca_id, descricao) values('102','IMPREZA');
insert into marca_modelo (marca_id, descricao) values('102','FORESTER');
insert into marca_modelo (marca_id, descricao) values('103','Wagon R+');
insert into marca_modelo (marca_id, descricao) values('103','Vitara');
insert into marca_modelo (marca_id, descricao) values('103','Swift');
insert into marca_modelo (marca_id, descricao) values('103','Santana');
insert into marca_modelo (marca_id, descricao) values('103','Samurai');
insert into marca_modelo (marca_id, descricao) values('103','Liana');
insert into marca_modelo (marca_id, descricao) values('103','Jimny');
insert into marca_modelo (marca_id, descricao) values('103','Ignis');
insert into marca_modelo (marca_id, descricao) values('103','Grand Vitara');
insert into marca_modelo (marca_id, descricao) values('103','Baleno');
insert into marca_modelo (marca_id, descricao) values('103','Alto');
insert into marca_modelo (marca_id, descricao) values('104','T4');
insert into marca_modelo (marca_id, descricao) values('104','RF');
insert into marca_modelo (marca_id, descricao) values('104','PANTANAL');
insert into marca_modelo (marca_id, descricao) values('105','UNIMOG');
insert into marca_modelo (marca_id, descricao) values('106','S60');
insert into marca_modelo (marca_id, descricao) values('106','S70');
insert into marca_modelo (marca_id, descricao) values('106','S80');
insert into marca_modelo (marca_id, descricao) values('106','V40');
insert into marca_modelo (marca_id, descricao) values('106','V50');
insert into marca_modelo (marca_id, descricao) values('106','V70');
insert into marca_modelo (marca_id, descricao) values('106','XC70');
insert into marca_modelo (marca_id, descricao) values('106','XC90');
insert into marca_modelo (marca_id, descricao) values('106','S40');
insert into marca_modelo (marca_id, descricao) values('106','C70');
insert into marca_modelo (marca_id, descricao) values('106','440');
insert into marca_modelo (marca_id, descricao) values('106','444');
insert into marca_modelo (marca_id, descricao) values('106','460');
insert into marca_modelo (marca_id, descricao) values('106','850');
insert into marca_modelo (marca_id, descricao) values('106','855');
insert into marca_modelo (marca_id, descricao) values('106','940');
insert into marca_modelo (marca_id, descricao) values('106','960');
insert into marca_modelo (marca_id, descricao) values('106','C30');
insert into marca_modelo (marca_id, descricao) values('107','WALKSPORT');
insert into marca_modelo (marca_id, descricao) values('108','CJ3A');
insert into marca_modelo (marca_id, descricao) values('108','AERO-WILLYS');
insert into marca_modelo (marca_id, descricao) values('108','JEEP');
insert into marca_modelo (marca_id, descricao) values('108','RURAL');
